stages:
    - test
    - deploy

test-job:
    stage: test
    script:
        - echo "Tested"

deploy-job:
    stage: deploy
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed."
