build-job:
  environment:
    name: develop
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - echo $DEBUG
    - echo "$DEBUG" > .env
    - test -f .env
  cache:
    paths: 
      - venv/
      - .env

test-job:
  environment:
    name: develop
  stage: test
  script:
      - test -f .env
