build-job:
  stage: build
  script:
    - python3 -m vevn venv
    - source /venv/bin/activate
    - pip3 install -r requirements.txt
    - echo "$DEBUG" > .env

test-build:
  stage: test
  script:
    - test -f .env
