build-job:
  environment: develop
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - echo "$DEBUG" > .env
    - test -f .env
