cache:
  paths: 
    - venv/
    - .env

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python3 --version  # For debugging
  - pip3 install virtualenv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt

create_env-job:
    environment:
      name: development
    script:
      - echo $DEBUG > .env
      - echo $SECRET_KEY >> .env
      - echo $ALLOWED_HOSTS >> .env
      - echo $DATABASE_URL >> .env
      - echo $CELERY_REDIS_URL >> .env
      - echo $ROSREESTR_POLICY_FILE >> .env
      - echo $ROSREESTR_OFFERTA_FILE >> .env
      - echo $TELEGRAM_API_TOKEN >> .env
      - echo $DADATA_TOKEN >> .env
      - echo $APIEGRN_TOKEN >> .env
      - echo $BASE_N_TOKEN >> .env
      - echo $FGIS_EGRN_TOKEN >> .env
      - echo $TINKOFF_TERMINAL >> .env
      - echo $TINKOFF_PASSWORD >> .env
      - echo $CACHING_MIDDLEWARE_REDIS_HOST >> .env
      - echo $CACHING_MIDDLEWARE_REDIS_PORT >> .env
      - echo $CACHING_MIDDLEWARE_REDIS_DB >> .env
      - echo $NOTIFIER_BOT_TOKEN >> .env
      - echo $ADMIN_GROUP_ID >> .env
    artifacts:
      expire_in: 30 days
      paths:
        - .env
      

build-job:
  environment:
    name: development
  stage: build
  script:
    - echo $DEBUG
    - echo "$DEBUG" > .env
    - test -f .env


test-job:
  environment:
    name: development
  stage: test
  script:
      - test -f .env
