cache:
  paths:
    - venv/
    - .env

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python3 --version  # For debugging
  - pip3 install virtualenv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt

create_env-job:
  except:
    - /^feature.*/
  stage: build
  environment:
    name: staging
  script:
    - echo "DEBUG=$DEBUG" > .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "ALLOWED_HOSTS=$ALLOWED_HOSTS" >> .env
    - echo "DATABASE_URL=$DATABASE_URL" >> .env
    - echo "CELERY_REDIS_URL=$CELERY_REDIS_URL" >> .env
    - echo "ROSREESTR_POLICY_FILE=$ROSREESTR_POLICY_FILE" >> .env
    - echo "ROSREESTR_OFFERTA_FILE=$ROSREESTR_OFFERTA_FILE" >> .env
    - echo "TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN" >> .env
    - echo "DADATA_TOKEN=$DADATA_TOKEN" >> .env
    - echo "APIEGRN_TOKEN=$APIEGRN_TOKEN" >> .env
    - echo "BASE_N_TOKEN=$BASE_N_TOKEN" >> .env
    - echo "FGIS_EGRN_TOKEN=$FGIS_EGRN_TOKEN" >> .env
    - echo "TINKOFF_TERMINAL=$TINKOFF_TERMINAL" >> .env
    - echo "TINKOFF_PASSWORD=$TINKOFF_PASSWORD" >> .env
    - echo "CACHING_MIDDLEWARE_REDIS_HOST=$CACHING_MIDDLEWARE_REDIS_HOST" >> .env
    - echo "CACHING_MIDDLEWARE_REDIS_PORT=$CACHING_MIDDLEWARE_REDIS_PORT" >> .env
    - echo "CACHING_MIDDLEWARE_REDIS_DB=$CACHING_MIDDLEWARE_REDIS_DB" >> .env
    - echo "NOTIFIER_BOT_TOKEN=$NOTIFIER_BOT_TOKEN" >> .env
    - echo "ADMIN_GROUP_ID=$ADMIN_GROUP_ID" >> .env
  artifacts:
    expire_in: 30 days
    paths:
      - .env

test-job:
  except:
    - /^feature.*/
  environment:
    name: staging
  stage: test
  script:
      - test -f .env

deploy-job:
  except:
    - /^feature.*/
  environment:
    name: staging
  stage: deploy
  script:
    - rsync -avz --exclude 'venv' -e 'ssh -p 34135' ./ web@193.164.150.71:/home/web/app/
    - ssh -p 34135 web@193.164.150.71 'cd /home/web/app; source prepear_venv.sh'
    - ssh -p 34135 web@193.164.150.71 'cd /home/web/app; source make_migrations.sh'
    - ssh -p 34135 avb@193.164.150.71 'cd /home/web/app; source supervisor_setup.sh'
    - ssh -p 34135 avb@193.164.150.71 'cd /home/web/app; source nginx_setup.sh'
  before_script:
    - echo "Start deploy to staging.."
