cache:
  paths: 
    - venv/
    - .env

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt

build-job:
  environment:
    name: development
  stage: build
  script:
    - echo $DEBUG
    - echo "$DEBUG" > .env
    - test -f .env

test-job:
  environment:
    name: develop
  stage: test
  script:
      - test -f .env
