import environ

env = environ.Env()
# управление проверкой SSL сертификата для сайта rosreestr.gov.ru
SSL_VERIFY = False

ROSREESTR_POLICY_FILE = env('ROSREESTR_POLICY_FILE')
ROSREESTR_OFFERTA_FILE = env('ROSREESTR_OFFERTA_FILE')

BACKEND = 'rr_backend.backend'

DEFAULT_CURENCY = 'руб'
RRTELEBOT_ORDERS_AGE = 30

TELEGRAM_API_TOKEN = env('TELEGRAM_API_TOKEN')
DADATA_TOKEN = env('DADATA_TOKEN')
APIEGRN_TOKEN = env('APIEGRN_TOKEN')
BASE_N_TOKEN = env('BASE_N_TOKEN')
FGIS_EGRN_TOKEN = env('FGIS_EGRN_TOKEN')
TINKOFF_TERMINAL = env('TINKOFF_TERMINAL')
TINKOFF_PASSWORD = env('TINKOFF_PASSWORD')

CACHING_MIDDLEWARE_REDIS_HOST = 'localhost'
CACHING_MIDDLEWARE_REDIS_PORT = 6379
CACHING_MIDDLEWARE_REDIS_DB = 3
NOTIFIER_BOT_TOKEN = env('NOTIFIER_BOT_TOKEN')
ADMIN_GROUP_ID = env('ADMIN_GROUP_ID')

FREE_SEARCH_MAX = 10
CASH_TTL = 60*60*24*7
