# Generated by Django 3.1.7 on 2021-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_key', models.TextField(max_length=20, verbose_name='Идентификатор терминала')),
                ('amount', models.IntegerField(verbose_name='Сумма (коп.)')),
                ('order_id', models.TextField(max_length=36, verbose_name='Идентификатор заказа у прдавца')),
                ('success', models.BooleanField(verbose_name='Выполнение платежа')),
                ('status', models.TextField(max_length=20, verbose_name='Статус платежа')),
                ('payment_id', models.IntegerField(verbose_name='Идентификатор платежа в системе банка')),
                ('error_code', models.TextField(blank=True, max_length=20, verbose_name='Код ошибки')),
                ('payment_url', models.URLField(blank=True, verbose_name='Ссылка на платежную форму')),
                ('message', models.TextField(blank=True, max_length=64, verbose_name='Краткое описание ошибки')),
                ('details', models.TextField(blank=True, max_length=256, verbose_name='Подробное описание ошибки')),
            ],
        ),
    ]
