# Generated by Django 3.1.7 on 2021-07-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_kassa', '0002_paymentmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='details',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='success',
        ),
    ]
