# Generated by Django 3.1.7 on 2021-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_kassa', '0003_auto_20210727_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
