---
- name: Deploy
  hosts: terragent.ru
  tasks:
    - name: Stop services
      community.general.supervisorctl:
        name: all
        state: stoped
    - name: Git checkout
      ansible.builtin.git:
        repo: 'git@github.com:avbskyfox/rosreestr.git'
        dest: app/rosreestr
        version: develop
    - name: Start services
      community.general.supervisorctl:
        name: all
        state: started